version: '1'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=Test01
      - POSTGRES_USER=friend
      - POSTGRES_DB=postgres